# Generated by Django 4.0.1 on 2022-04-05 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_wallet_employee_wallet_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='core.company'),
        ),
    ]
