# Generated by Django 4.0.1 on 2022-05-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_payment_payment_from_alter_payment_payment_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tin_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='company tin number'),
        ),
    ]
