# Generated by Django 4.0.1 on 2022-05-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_company_tin_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('API_KEY', models.CharField(max_length=255, verbose_name='api key')),
                ('device', models.CharField(max_length=255, verbose_name='device number')),
                ('sim', models.CharField(max_length=255, verbose_name='sim card number')),
                ('server', models.CharField(max_length=255, verbose_name='server url')),
            ],
        ),
    ]
