# Generated by Django 4.0.1 on 2022-05-30 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_config'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config',
        ),
    ]
