# Generated by Django 4.0.1 on 2022-06-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255)),
                ('server', models.CharField(max_length=255)),
                ('sim', models.IntegerField()),
                ('device', models.IntegerField()),
            ],
        ),
    ]
